- hosts: slave1
  become: yes
  become_user: root
  vars_files: vars/default.yml
  tasks:
    - name: Installation software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 8.1
      apt:
       name: php7.4
       state: present
       
  - name: Update "apt"
      apt:
       update_cache: yes
       autoclean: yes

    - name: Install PHP Modules
      apt:
       pkg:
       - php7.4-cli
       - php7.4-common
       - php7.4-mysql
       - php7.4-zip
       - php7.4-gd
       - php7.4-mbstring
       - php7.4-curl
       - php7.4-curl
       - php7.4-xml
       - php7.4-bcmath
       - libapache2-mod-php

    - name: Allow HTTP
      ufw:
       rule: allow
       port: "80"
       proto: tcp

    - name: Allow HTTPS
      ufw:
       rule: allow
       port: "443"
       proto: tcp

    - name: Allow SSH
      ufw:
       rule: allow
       port: "22"
       proto: tcp

    - name: Allow MySQL
      ufw:
       rule: allow
       port: "3306"
       proto: tcp

    - name: Update "apt"
      apt:
       update_cache: yes
       autoclean: yes
       autoremove: yes

    - name: Install python3
      apt:
       name: python3
       state: present

    - name: Install pip
      apt:
       name: python3-pip
       state: present
      with_items:
        - acl
        - python3-pip

    - name: Install MySQL
      apt:
       pkg:
       - mysql-server
       - mysql-client
       - python3-mysqldb
       - libmysqlclient-dev

    - name: Install PyMySQL
      pip:
       name: pymysql
       state: present

    - name: Start the MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Clone the project repo into a new directory
      git:
        repo: https://github.com/f1amy/laravel-realworld-example-app
        dest: /var/www/myapp
        clone: yes
        update: no

    - name: Create the web.php file in the routes directory
      ansible.builtin.copy:
        dest: /var/www/myapp/routes/web.php
        content: |
          <?php

           Route::get('/', function () {
               return view('welcome');
           });

    - name: Create an apache virtual host configuration file
      ansible.builtin.copy:
        dest: /var/www/myapp/.env
        content: |
          APP_NAME="Laravel Realworld Example App"
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://papapeli.me
          APP_PORT=3000

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=localhost
          DB_PORT=330
          DB_DATABASE=laravel_realworld
          DB_USERNAME="root"
          DB_PASSWORD="1234"

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1
          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_MAILER=smtp
          MAIL_HOST=mailhog
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="gloryyusuf20@gmail.com"
          MAIL_FROM_ADDRESS="Laravel Real World Example App"

          AWS_ACCESS_KEY_ID=AKIAWLYMALNUVNPTYOHK
          AWS_SECRET_KEY_ID=A9fP741jZjAWLIJ2rNH26wHxTpJq352knAOqK39L
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_APP_CLUSTER=mt1

          MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"

          MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

          L5_SWAGGER_GENERATE_ALWAYS=true
          SAIL_XDEBUG_MODE=develop,debug
          SAIL_SKIP_CHECKS=true

    - name: Make composer executable by user
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    - name: Run the php artisan command
      ansible.builtin.shell: php artisan key:generate
      args:
       chdir: /var/www/myapp

    - name: Run the other php artisan command
      ansible.builtin.shell: php artisan config:cache
      args:
       chdir: /var/www/myapp

    - name: Run the third config
      ansible.builtin.shell: sudo php artisan view:clear
      args:
       chdir: /var/www/myapp

    - name: Run the migration
      ansible.builtin.shell: sudo php artisan migrate
      args:
       chdir: /var/www/myapp

    - name: Create an apache virtual host configuration file
      ansible.builtin.copy:
        dest: /etc/apache2/sites-available/papapeli.me.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin admin@papapeli.me
              ServerName papapeli.me
              ServerAlias www.papapeli.me
              DocumentRoot /var/www/myapp/public

              <Directory /var/www/myapp/public>
                  AllowOverride All
              </Directory>

              ErrorLog /var/www/myapp/storage/error.log
              CustomLog /var/www/myapp/storage/access.log combined
          </VirtualHost>

    - name: Enable a2enmod rewrite
      ansible.builtin.command: /usr/sbin/a2enmod rewrite

    - name: Disable default apache page and enable laravel page
      file: >
        path=/etc/apache2/sites-available/000-default.conf
        state=absent
      when: disable_default
      notify: Reload Apache

    - name: Enable laravel page
      ansible.builtin.command: a2ensite papapeli.me
      args:
        creates: /etc/apache2/sites-enabled/papapeli.me
      notify:
      - Restart apache2       
